<link href="{{asset('bower_components/metronic-admin/vendors/perfect-scrollbar/css/perfect-scrollbar.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/tether/dist/css/tether.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-datetime-picker/css/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-timepicker/css/bootstrap-timepicbower_components/ker.min.-admincss')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-select/dist/css/bootstrap-select.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/select2/dist/css/select2.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/nouislider/distribute/nouislider.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/owl.carousel/dist/assets/owl.carousel.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/owl.carousel/dist/assets/owl.theme.default.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/ion-rangeslider/css/ion.rangeSlider.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/ion-rangeslider/css/ion.rangeSlider.skinFlat.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/dropzone/dist/dropzone.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/summernote/dist/summernote.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/bootstrap-markdown/css/bootstrap-markdown.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/animate.css/animate.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/toastr/build/toastr.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/jstree/dist/themes/default/style.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/morris.js/morris.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/chartist/dist/chartist.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/sweetalert2/dist/sweetalert2.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/socicon/css/socicon.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/vendors/line-awesome/css/line-awesome.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/vendors/flaticon/css/flaticon.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/vendors/metronic/css/styles.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/vendors/vendors/fontawesome5/css/all.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/assets/demo/base/style.bundle.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('bower_components/metronic-admin/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css')}}" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="{{asset('bower_components/metronic-admin/assets/demo/media/img/logo/favicon.ico')}}" />
<link rel="shortcut icon" href="{{asset('bower_components/sweetalert2/src/sweetalert2.scss')}}" />

<link rel="stylesheet" href="{{asset('css/custom.css')}}" />
