<script src="{{asset('bower_components/metronic-admin/vendors/jquery/dist/jquery.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/popper.js/dist/umd/popper.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap/dist/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js-cookie/src/js.cookie.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/moment/min/moment.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/tooltip.js/dist/umd/tooltip.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/perfect-scrollbar/dist/perfect-scrollbar.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/wnumb/wNumb.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery.repeater/src/lib.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery.repeater/src/jquery.input.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery.repeater/src/repeater.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery-form/dist/jquery.form.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/block-ui/jquery.blockUI.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/bootstrap-datepicker.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-datetime-picker/js/bootstrap-datetimepicker.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-timepicker/js/bootstrap-timepicker.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/bootstrap-timepicker.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-daterangepicker/daterangepicker.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/bootstrap-daterangepicker.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-maxlength/src/bootstrap-maxlength.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-switch/dist/js/bootstrap-switch.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/bootstrap-switch.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/vendors/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-select/dist/js/bootstrap-select.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/select2/dist/js/select2.full.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/typeahead.js/dist/typeahead.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/handlebars/dist/handlebars.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/inputmask/dist/jquery.inputmask.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/inputmask/dist/inputmask/inputmask.date.extensions.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/inputmask/dist/inputmask/inputmask.numeric.extensions.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/inputmask/dist/inputmask/inputmask.phone.extensions.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/nouislider/distribute/nouislider.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/owl.carousel/dist/owl.carousel.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/autosize/dist/autosize.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/clipboard/dist/clipboard.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/ion-rangeslider/js/ion.rangeSlider.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/dropzone/dist/dropzone.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/summernote/dist/summernote.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/markdown/lib/markdown.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-markdown/js/bootstrap-markdown.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/bootstrap-markdown.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery-validation/dist/jquery.validate.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jquery-validation/dist/additional-methods.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/forms/jquery-validation.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/bootstrap-notify/bootstrap-notify.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/base/bootstrap-notify.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/toastr/build/toastr.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/jstree/dist/jstree.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/raphael/raphael.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/morris.js/morris.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/chartist/dist/chartist.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/chart.js/dist/Chart.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/charts/chart.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/vendors/bootstrap-session-timeout/dist/bootstrap-session-timeout.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/vendors/jquery-idletimer/idle-timer.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/waypoints/lib/jquery.waypoints.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/counterup/jquery.counterup.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/es6-promise-polyfill/promise.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/sweetalert2/dist/sweetalert2.min.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/vendors/js/framework/components/plugins/base/sweetalert2.init.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/assets/demo/base/scripts.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/assets/vendors/custom/fullcalendar/fullcalendar.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/assets/app/js/dashboard.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/assets/demo/widgets/summernote.js')}}" type="text/javascript"></script>
<script src="{{asset('bower_components/metronic-admin/assets/demo/widgets/bootstrap-datepicker.js')}}" type="text/javascript"></script>

<script src="{{asset('js/admin.js')}}" type="text/javascript"></script>
<script src="{{asset('js/bootstrap.js')}}" type="text/javascript"></script>

